app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: registry-mirror.e-whisper.com/excalidraw/excalidraw
            tag: latest
  service:
    main:
      ports:
        http:
          port: 80
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: tailscale
      annotations:
        tailscale.com/funnel: "true"
      hosts:
        - host: &host draw.west-beta.ts.net
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
