zot:
  ingress:
    enabled: true
    className: tailscale
    hosts:
      - host: &host registry.west-beta.ts.net
        paths:
          - path: /
    tls:
      - hosts:
          - *host
  # TODO enable auth
  persistence: true
  pvc:
    create: true
    storage: 10Gi
