apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: auth.west-beta.ts.net
    tailscale.com/proxy-group: ts-proxies
  name: egress-auth
  namespace: {{ .Release.Namespace }}
spec:
  externalName: unused
  type: ExternalName
  ports:
    - port: 443
      protocol: TCP
