- name: Create Kubernetes cluster
  hosts: metal
  become: true
  roles:
    - prerequisites
    - k3s
    - automatic_upgrade

- name: Install prometheus-operator-crds
  hosts: localhost
  roles:
    - prometheus_operator_crds

- name: Install Kubernetes addons
  hosts: localhost
  roles:
    - cilium

- name: Install tailscale-operator
  hosts: localhost
  roles:
    - tailscale
