all:
  vars:
    control_plane_endpoint: 192.168.3.100
    load_balancer_ip_pool:
      - 192.168.3.32/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.3.154, mac: '00:f0:4d:00:0c:7d', disk: nvme0n1p4, network_interface: enp2s0}
    workers:
      hosts:
