# Duplicate tasks, same as ./metal/roles/pxe_server/tasks/main.yml
# TODO:
- name: Set ipv4 net_mask variable
  set_fact:
    ipv4_net_mask: "{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"

- name: Display the ipv4 net_mask variable
  debug:
    msg: "ipv4 net_mask: {{ ipv4_net_mask }}"

# Make sure the hubble grafana dashboards can install
- name: Create the monitoring-system namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: monitoring-system

- name: Install Cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium
    chart_repo_url: "{{ cilium_repo_url }}"
    chart_version: "{{ cilium_version }}"
    release_namespace: "{{ cilium_namespace }}"
    values: "{{ cilium_values }}"

- name: Wait for Cilium CRDs
  kubernetes.core.k8s_info:
    kind: CustomResourceDefinition
    name: "{{ item }}"
  loop:
    - ciliuml2announcementpolicies.cilium.io
    - ciliumloadbalancerippools.cilium.io
  register: crd
  until: crd.resources | length > 0
  retries: 5
  delay: 10

- name: Apply Cilium resources
  kubernetes.core.k8s:
    template: "{{ item }}"
  loop:
    - ciliuml2announcementpolicy.yaml
    - ciliumloadbalancerippool.yaml
