app-template:
  controllers:
    main:
      type: statefulset
      containers:
        main:
          image:
            repository: registry-mirror.e-whisper.com/kanidm/server
            tag: 1.3.3
      statefulset:
        volumeClaimTemplates:
          - name: data
            size: 1Gi
            globalMounts:
              - path: /data
            accessMode: "ReadWriteOnce"
  configMaps:
    config:
      enabled: true
      data:
        server.toml: |
          bindaddress = "[::]:443"
          ldapbindaddress = "[::]:636"
          trust_x_forward_for = true
          db_path = "/data/kanidm.db"
          tls_chain = "/data/ca.crt"
          tls_key = "/data/tls.key"
          domain = "auth.west-beta.ts.net"
          origin = "https://auth.west-beta.ts.net"
  service:
    main:
      ports:
        http:
          enabled: false
        https:
          port: 443
          protocol: HTTPS
        ldap:
          port: 636
          protocol: TCP
  ingress:
    main:
      enabled: true
      className: tailscale
      annotations:
        tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
      hosts:
        - host: &host auth.west-beta.ts.net
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: https
      tls:
        - hosts:
            - *host
  persistence:
    config:
      enabled: true
      type: configMap
      name: kanidm-config
      globalMounts:
        - path: /data/server.toml
          subPath: server.toml
    tls:
      enabled: true
      type: secret
      name: kanidm-selfsigned-certificate
      globalMounts:
        - path: /data/ca.crt
          subPath: ca.crt
        - path: /data/tls.key
          subPath: tls.key
