apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: ci.west-beta.ts.net
  name: egress-ci
  namespace: {{ .Release.Namespace }}
spec:
  externalName: unused
  type: ExternalName
