apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: git.west-beta.ts.net
  name: egress-git
  namespace: {{ .Release.Namespace }}
spec:
  externalName: unused
  type: ExternalName
