- name: Install packages for automatic upgrade
  ansible.builtin.apt:
    name:
      - apt-utils
      - unattended-upgrades
      - update-notifier-common

- name: Copy unattended-upgrades config file
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/apt/apt.conf.d/{{ item }}
    mode: 0644
  loop:
    - 20auto-upgrades
    - 50unattended-upgrades

- name: Enable unattended-upgrades service
  ansible.builtin.systemd:
    name: unattended-upgrades.service
    state: started
    enabled: true
