elementweb:
  ingress:
    enabled: true
    className: tailscale
    annotations:
      tailscale.com/funnel: "true"
    hosts:
      - host: &frontend_host chat.west-beta.ts.net
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - *frontend_host
  config:
    default:
      base_url: https://matrix.west-beta.ts.net
      server_name: matrix.west-beta.ts.net

dendrite:
  dendrite_config:
    global:
      server_name: matrix.west-beta.ts.net
  ingress:
    enabled: true
    className: tailscale
    hostName: matrix.west-beta.ts.net
    tls:
      - hosts:
          - matrix.west-beta.ts.net
  postgresql:
    enabled: true
