woodpecker:
  agent:
    replicaCount: 2
    env:
      WOODPECKER_BACKEND_K8S_STORAGE_RWX: false
      # Agents will spawn pods to run workflow steps using the
      # Kubernetes backend instead of running them directly on
      # the agent pod, so we can run many workflows per agent.
      WOODPECKER_MAX_WORKFLOWS: 10
  server:
    env:
      WOODPECKER_HOST: https://ci.west-beta.ts.net
      WOODPECKER_WEBHOOK_HOST: http://woodpecker-server.woodpecker
      WOODPECKER_GITEA: true
      WOODPECKER_GITEA_URL: https://git.west-beta.ts.net
      WOODPECKER_OPEN: true
      WOODPECKER_ADMIN: gitea_admin
    ingress:
      enabled: true
      ingressClassName: tailscale
      annotations:
        tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
      hosts:
        - host: &host ci.west-beta.ts.net
          paths:
            - path: /
      tls:
        - hosts:
            - *host
