- hosts: localhost
  tasks:
    - name: Ensure required namespaces exist
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ item }}"
        state: present
      loop:
        - tailscale
        - external-dns
        - global-secrets
        - grafana
        - monitoring-system
